### Upload all researchers avatars

PUT http://localhost:9080/ResearchManager/api/researchers/5ba66330-942c-4ae6-9cb7-e2e2f9628b9a/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="madison.png"

< src/main/resources/madison.png

--boundary

###

PUT http://localhost:9080/ResearchManager/api/researchers/b8c250ba-ac86-4563-a42a-563f7962f353/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="jason.png"

< src/main/resources/jason.png

--boundary

###

PUT http://localhost:9080/ResearchManager/api/researchers/b8371a52-2d1a-4af9-a5ba-15934740e3e1/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="clayre.png"

< src/main/resources/clayre.png

--boundary

###

PUT http://localhost:9080/ResearchManager/api/researchers/d91b3081-fce5-4605-9082-e123b10f7ade/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="mark.png"

< src/main/resources/mark.png

--boundary

###

PUT http://localhost:9080/ResearchManager/api/researchers/88e9ccfb-b924-4988-bcb2-f84e7f7810d7/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="jonathan.png"

< src/main/resources/jonathan.png