### Get all researchers

GET http://localhost:9080/ResearchManager/api/researchers

### Create researcher

PUT http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c
Content-Type: application/json

{
  "login": "john",
  "firstName": "John",
  "lastName": "Smith",
  "role": "LEAD_RESEARCHER",
  "birthDate": "1980-01-01",
  "password": "password",
  "email": "john@jee.com"
}

### Get researcher by id

GET http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c

### Update researcher

PATCH http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c
Content-Type: application/json

{
  "login": "john",
  "firstName": "John",
  "lastName": "Lennon",
  "role": "LEAD_RESEARCHER",
  "birthDate": "1985-05-05",
  "password": "password",
  "email": "john@jee.com"
}

### Create researcher avatar

PUT http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="john.png"

< src/main/resources/john.png
--boundary

### Get researcher avatar

GET http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar

### Update researcher avatar

PATCH http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="madison.png"

< src/main/resources/madison.png
--boundary

### Delete researcher avatar

DELETE http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar

### Delete researcher

DELETE http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c

### Get all projects

GET http://localhost:9080/ResearchManager/api/projects

### Create project

PUT http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f
Content-Type: application/json

{
  "title": "Project 1",
  "budget": 12345.67,
  "priority": "LOW"
}

### Get project by id

GET http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f

### Update project

PATCH http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f
Content-Type: application/json

{
  "title": "First Project",
  "budget": 76543.21,
  "priority": "HIGH"
}

### Delete project

DELETE http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f

### Get all experiments

GET http://localhost:9080/ResearchManager/api/experiments

### Create experiment

PUT http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f/experiments/4141cca1-25f6-4635-a86e-39f911a8db3e
Content-Type: application/json

{
  "description": "Description 1",
  "success": true,
  "dateConducted": "2024-10-24"
}

### Get experiment by id

GET http://localhost:9080/ResearchManager/api/experiments/4141cca1-25f6-4635-a86e-39f911a8db3e

### Get project experiments

GET http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f/experiments

### Update experiment

PATCH http://localhost:9080/ResearchManager/api/experiments/4141cca1-25f6-4635-a86e-39f911a8db3e
Content-Type: application/json

{
  "description": "First Description",
  "success": false,
  "dateConducted": "2024-10-25"
}

### Delete experiment

DELETE http://localhost:9080/ResearchManager/api/experiments/4141cca1-25f6-4635-a86e-39f911a8db3e