# clayre (admin) Authorization: Basic Y2xheXJlOnBhc3N3b3Jk
# jonathan (user) Authorization: Basic am9uYXRoYW46cGFzc3dvcmQ=
# jason (user) Authorization: Basic amFzb246cGFzc3dvcmQ=

### Get all researchers
// @no-cookie-jar
GET http://localhost:9080/ResearchManager/api/researchers
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk

### Create researcher
// @no-cookie-jar
PUT http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c
Content-Type: application/json

{
  "login": "john",
  "firstName": "John",
  "lastName": "Smith",
  "role": "admin",
  "birthDate": "1980-01-01",
  "password": "password",
  "email": "john@jee.com"
}

### Get researcher by id
// @no-cookie-jar
GET http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk

### Get researcher experiments
// @no-cookie-jar
GET http://localhost:9080/ResearchManager/api/researchers/b8371a52-2d1a-4af9-a5ba-15934740e3e1/experiments
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk

### Update researcher
// @no-cookie-jar
PATCH http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk
Content-Type: application/json

{
  "firstName": "James",
  "lastName": "Lennon",
  "birthDate": "1985-05-05"
}

### Create researcher avatar
// @no-cookie-jar
PUT http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="john.png"

< src/main/resources/john.png
--boundary

### Get researcher avatar
// @no-cookie-jar
GET http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk

### Update researcher avatar
// @no-cookie-jar
PATCH http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="madison.png"

< src/main/resources/madison.png
--boundary

### Delete researcher avatar
// @no-cookie-jar
DELETE http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk

### Delete researcher
// @no-cookie-jar
DELETE http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk

### Get all projects
// @no-cookie-jar
GET http://localhost:9080/ResearchManager/api/projects
Authorization: Basic am9uYXRoYW46cGFzc3dvcmQ=

### Create project
// @no-cookie-jar
PUT http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk
Content-Type: application/json

{
  "title": "Project 1",
  "budget": 12345.67,
  "priority": "LOW"
}

### Get project by id
// @no-cookie-jar
GET http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk

### Update project
// @no-cookie-jar
PATCH http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk
Content-Type: application/json

{
  "title": "First Project",
  "budget": 76543.21,
  "priority": "HIGH"
}

### Delete project
// @no-cookie-jar
DELETE http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk

### Get all experiments
// @no-cookie-jar
GET http://localhost:9080/ResearchManager/api/experiments
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk

### Create experiment
// @no-cookie-jar
PUT http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f/experiments/4141cca1-25f6-4635-a86e-39f911a8db3e
Authorization: Basic am9uYXRoYW46cGFzc3dvcmQ=
Content-Type: application/json

{
  "description": "Description 1",
  "success": true,
  "dateConducted": "2024-10-24"
}

### Get experiment by id
// @no-cookie-jar
GET http://localhost:9080/ResearchManager/api/experiments/4141cca1-25f6-4635-a86e-39f911a8db3e
Authorization: Basic am9uYXRoYW46cGFzc3dvcmQ=

### Get project experiments
// @no-cookie-jar
GET http://localhost:9080/ResearchManager/api/projects/fe9d920d-f836-44c1-9281-dc4a080a9f0f/experiments
Authorization: Basic Y2xheXJlOnBhc3N3b3Jk

### Update experiment
// @no-cookie-jar
PATCH http://localhost:9080/ResearchManager/api/experiments/4141cca1-25f6-4635-a86e-39f911a8db3e
Authorization: Basic am9uYXRoYW46cGFzc3dvcmQ=
Content-Type: application/json

{
  "description": "First Description",
  "success": false,
  "dateConducted": "2024-10-25"
}

### Delete experiment
// @no-cookie-jar
DELETE http://localhost:9080/ResearchManager/api/experiments/4141cca1-25f6-4635-a86e-39f911a8db3e
Authorization: Basic am9uYXRoYW46cGFzc3dvcmQ=