### Get all researchers

GET http://localhost:9080/ResearchManager/api/researchers

### Get researcher by id

GET http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c

### Create researcher

PUT http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c
Content-Type: application/json

{
  "login": "john",
  "firstName": "John",
  "lastName": "Smith",
  "role": "LEAD_RESEARCHER",
  "birthDate": "1980-01-01",
  "password": "password",
  "email": "john@jee.com"
}

### Update researcher

PATCH http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c
Content-Type: application/json

{
  "login": "john",
  "firstName": "John",
  "lastName": "Lennon",
  "role": "LEAD_RESEARCHER",
  "birthDate": "1985-05-05",
  "password": "password",
  "email": "john@jee.com"
}

### Delete user

DELETE http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c

### Get researcher avatar

GET http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar

### Delete researcher avatar

DELETE http://localhost:9080/ResearchManager/api/researchers/b8371a52-2d1a-4af9-a5ba-15934740e3e1/avatar

### Create researcher avatar

PUT http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="john.png"

< src/main/resources/lab/jee/configuration/avatar/john.png
--boundary

### Get researcher avatar

GET http://localhost:9080/ResearchManager/api/researchers/1a8bc5d1-0219-4172-9d6a-85154079ff0c/avatar

### Update researcher avatar

PATCH http://localhost:9080/ResearchManager/api/researchers/b8371a52-2d1a-4af9-a5ba-15934740e3e1/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="madison.png"

< src/main/resources/lab/jee/configuration/avatar/madison.png
--boundary

### Get all projects

GET http://localhost:9080/ResearchManager/api/projects

### Get project by id

GET http://localhost:9080/ResearchManager/api/projects/9ba4a53d-e742-40cb-a613-f609696c5ef9

### Get all experiments

GET http://localhost:9080/ResearchManager/api/experiments

### Get experiment by id

GET http://localhost:9080/ResearchManager/api/experiments/3180349a-7d53-4200-91dc-3b0b757dca98